#
# Docker container for testing odybcl2fastq
#
FROM centos:7.4.1708

RUN yum -y update && yum install -y python wget mysql-devel gcc make python-devel unzip libffi-devel libssl-devel pyOpenSSL
RUN yum -y install epel-release
RUN yum -y install python-pip

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

RUN wget https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip && unzip *.zip && rpm -i *.rpm

ADD . /app

RUN pip install nose

ENV PYTHONPATH=/app
ENV ODYBCL2FASTQ_CONFIG_FILE=/app/test/test.config.json

CMD ["nosetests", "-vv"]
